language: node_js
node_js:
        - 13
services:
        - docker
# Pre-testing installs
install:
        - echo "nothing need to be inistalled"
# Scripts to be run as tests
before_script:
        - echo "no tests"
script:
        - cd ./simple-node/
        - docker --version # print the version for logging
        - docker build -t harroshan/simple-node .
after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push harroshan/simple-node
